### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by githublizhipan** [ZAX130/SmileCode#5]
您好，我是一个刚接触医学图像处理的学生，想运行一下您的代码，但是您给的数据集链接里有很多个LPBA，我不确定下载哪一个，您可以详细说明一下应该下载哪一个数据集吗？谢谢！

**Comment by ZAX130** [comment]
【基于深度学习的单模医学图像配准综述（附VoxelMorph配准实例） -  CSDN App】http://t.csdnimg.cn/8k0yP
