### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by shy922** [ZAX130/SmileCode#6]
Mindboggle数据集如何进行实验

**Comment by ZAX130** [comment]
里面有若干子集，包括oasis，mmrr等。每例数据都包含了仿射，未仿射，手工分割，软件分割等，都是nii.gz格式。根据习惯，每位作者用的设定可能有所差别

**Comment by shy922** [comment]
如何计算ASSD，您的代码中没有 可以请教一下吗

**Comment by ZAX130** [comment]
pip install medpy

**Comment by shy922** [comment]
好的 谢谢
