### ISSUE TITLE
图像尺寸

### ISSUE THREAD

**Issue by yesstarA** [ZAX130/SmileCode#7]
你好！我想请教以下几个问题：
1.如何裁剪mind101数据集的尺寸大小？另外我在官网似乎没有看到label的注释，预处理数据集的时候seg_norm的标签怎么填写呢？
2.想问一下modeT能否运行160，192，224的图像？
3.运行30epoch的modeT大约需要多久？我跑了几轮感觉时间略久
感谢！

**Comment by ZAX130** [comment]
裁剪根据分割裁，seg_norm根据图像分割标签具体内容填的，这个函数根据用户需求来决定是否填写。
大图像能不能运行看显卡。
模型推理速度和显存占用问题我们在优化代码，将在这一两个月发出来
